# 3 - Numbers, Dates, and Times

## Rounding Numerical Values

In [1]:
round(1.23, 1)

1.2

In [2]:
round(1.27, 1)

1.3

In [3]:
round(14210, -3)

14000

## Performing Accurate Decimal Calculations
Even simple mathematical calculations introduce small errors:

In [4]:
a = 4.2
b = 2.1
a + b

6.300000000000001

In [5]:
(a + b) == 6.3

False

In [6]:
round(a + b, 2) == 6.3

True

Use the decimal module for more accuracy. The decimal module implements IBM’s 'General Decimal Arithmetic Specification.'

In [7]:
from decimal import Decimal

a = Decimal('4.2')
b = Decimal('2.1')
a + b

Decimal('6.3')

In [8]:
(a + b) == Decimal('6.3')

True

In [10]:
from decimal import localcontext

a = Decimal('1.3')
b = Decimal('1.7')
a / b

Decimal('0.7647058823529411764705882353')

In [11]:
with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)

0.765


## Formatting Numbers for Output
Use the built-in format() function.

In [2]:
x = 1234.56789
x

1234.56789

In [3]:
format(x, '0.2f')  # to 2dp

'1234.57'

In [4]:
format(x, '>10.1f')  # right justified in 10 chars, one-digit accuracy

'    1234.6'

In [5]:
format(x, '<10.1f')  # left justified

'1234.6    '

In [7]:
format(x, '^10.1f')  # centred

'  1234.6  '

In [8]:
format(x, ',')  # using the thousands separator

'1,234.56789'

In [9]:
format(x, '0,.2f')

'1,234.57'

In [10]:
format(x, 'e')

'1.234568e+03'

In [11]:
format(x, '0.2E')

'1.23E+03'

In [12]:
'The value is {:0,.2f}'.format(x)

'The value is 1,234.57'

## Working with Binary, Octal, and Hexadecimal Integers
Use the bin(), oct(), or hex() functions, respectively.

In [14]:
x = 1234
x

1234

In [15]:
bin(x)

'0b10011010010'

In [16]:
oct(x)

'0o2322'

In [17]:
hex(x)

'0x4d2'

In [18]:
format(x, 'b'), format(x, 'o'), format(x, 'x')

('10011010010', '2322', '4d2')

## Packing and Unpacking Large Integers from Bytes

In [19]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
data

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [21]:
len(data)

16

In [23]:
int.from_bytes(data, "little")

69120565665751139577663547927094891008

In [24]:
int.from_bytes(data, "big")

94522842520747284487117727783387188

And int to bytes.

In [25]:
x = 94522842520747284487117727783387188
x

94522842520747284487117727783387188

In [26]:
x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [27]:
x.to_bytes(16, 'little')

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

## Performing Complex-Valued Math

In [28]:
a = complex(2, 4)
a

(2+4j)

In [29]:
b = 3 - 5j
b

(3-5j)

The real, imaginary, and conjugate values are easy to obtain.

In [30]:
a.real

2.0

In [31]:
a.imag

4.0

In [32]:
a.conjugate()

(2-4j)

In [33]:
a+b, a*b, a / b

((5-1j), (26+2j), (-0.4117647058823529+0.6470588235294118j))

## Working with Infinity and NaNs

In [1]:
a = float('inf')
a

inf

In [2]:
b = float('-inf')
b

-inf

In [3]:
c = float('nan')
c

nan

In [4]:
c + 2.2

nan

In [6]:
import math

math.isinf(a)

True

In [7]:
math.isnan(c)

True

## Calculating with Fractions

In [9]:
from fractions import Fraction

a = Fraction(1, 2)
a

Fraction(1, 2)

In [10]:
b = Fraction(1, 4)
b

Fraction(1, 4)

In [13]:
c = a + b
c

Fraction(3, 4)

In [14]:
c.numerator

3

In [15]:
c.denominator

4

In [16]:
float(c)

0.75

## Calculating with Large Numerical Arrays
Use numpy...

In [21]:
import numpy as np

a = list(range(1, 1001))
b = np.array(a)

In [22]:
%%timeit
sum(a)

8.06 µs ± 65.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%%timeit
np.sum(b)

3.46 µs ± 36.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


There is an overhead with numpy, so smaller arrays will be faster through the standard library. NumPy is the foundation for a huge number of science and engineering libraries in Python. It is also one of the largest and most complicated modules in widespread use.

## Performing Matrix and Linear Algebra Calculations

In [24]:
import numpy as np

m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [25]:
m.T  # transpose

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [26]:
m.I  # inverse

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [27]:
v = np.matrix([[2],[3],[4]])
v

matrix([[2],
        [3],
        [4]])

In [28]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

In [29]:
np.linalg.det(m)  # determinant

-229.99999999999983

In [30]:
np.linalg.eigvals(m)  # eigenvalues

array([-13.11474312,   2.75956154,   6.35518158])

In [33]:
# solve for x in mx = v
x = np.linalg.solve(m, v)
x

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

In [34]:
m * x

matrix([[2.],
        [3.],
        [4.]])

## Picking Things at [Random](https://docs.python.org/3/library/random.html)

In [38]:
import random

values = [1, 2, 3, 4, 5, 6]

In [39]:
random.choice(values)

5

In [37]:
random.sample(values, 2)

[1, 3]

In [40]:
random.shuffle(values)
values

[5, 6, 4, 2, 1, 3]

In [41]:
random.randint(0,10)

6

In [42]:
random.random()

0.26770465170782587

## Converting Days to Seconds, and Other Basic Time Conversions